version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO: 779846797240.dkr.ecr.us-east-1.amazonaws.com/employee-department1
    IMAGE_TAG: latest
    EXECUTION_ROLE_ARN: arn:aws:iam::779846797240:role/ecsTaskExecutionRole
    LOG_GROUP: /ecs/employee-department1
    SONAR_PROJECT_KEY: employee-department-1
    SONAR_HOST_URL: http://sonarqube.sivendar.click:9000

  secrets-manager:
    SONAR_TOKEN: sonar_token

phases:
  install:
    runtime-versions:
      java: corretto21  # Update to match <release>21 in pom.xml
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - echo Setting up Sonar Scanner...
      - export PATH=$PATH:/root/.sonar/scanner/bin
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN || echo "Sonar scan skipped"

  build:
    commands:
      - echo Building the project...
      - mvn clean package -DskipTests
      - echo Building Docker image...
      - docker build -t employee-department1 -f Docker/Dockerfile .
      - docker tag employee-department1:latest $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"employee-department1","imageUri":"%s"}]' "$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json
      - echo Deploying to ECS...
      - |
        aws ecs update-service \
          --cluster employee-cluster \
          --service employee-department1-service \
          --force-new-deployment \
          --region $AWS_REGION

artifacts:
  files:
    - target/*.jar
