version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    CLUSTER_NAME: employee-cluster1
    SERVICE_NAME: employee-service
    IMAGE_TAG: latest
    TASK_DEF_NAME: employee-taskdef
    ECR_REPO: 779846797240.dkr.ecr.us-east-1.amazonaws.com/employee-department1
    SUBNET_IDS: subnet-0c06c9ba80675ca5b
    SECURITY_GROUP_IDS: sg-03992897fd20860bd
    LOG_GROUP: /ecs/employee-department1
    EXECUTION_ROLE_ARN: arn:aws:iam::779846797240:role/ecsTaskExecutionRole

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo Installing AWS CLI...
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo Building Maven package...
      - mvn clean package -DskipTests
      - echo Building Docker image...
      - docker build -t employee-department1 -f Docker/Dockerfile .
      - docker tag employee-department1:latest $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Creating CloudWatch log group if not exists...
      - aws logs create-log-group --log-group-name "$LOG_GROUP" --region $AWS_REGION || echo "Log group already exists"

      - echo Registering task definition...
      - |
        printf '{
          "family": "%s",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "512",
          "memory": "1024",
          "executionRoleArn": "%s",
          "containerDefinitions": [
            {
              "name": "employee-department1",
              "image": "%s:%s",
              "portMappings": [
                {
                  "containerPort": 8080,
                  "protocol": "tcp"
                }
              ],
              "essential": true,
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "%s",
                  "awslogs-region": "%s",
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }
          ]
        }' "$TASK_DEF_NAME" "$EXECUTION_ROLE_ARN" "$ECR_REPO" "$IMAGE_TAG" "$LOG_GROUP" "$AWS_REGION" > taskdef.json

      - aws ecs register-task-definition \
          --cli-input-json file://taskdef.json \
          --region $AWS_REGION

      - echo Checking ECS service status...
      - |
        SERVICE_STATUS=$(aws ecs describe-services \
          --cluster $CLUSTER_NAME \
          --services $SERVICE_NAME \
          --region $AWS_REGION \
          --query "services[0].status" \
          --output text 2>/dev/null || echo "NOT_FOUND")

        echo "Service status: $SERVICE_STATUS"

        if [ "$SERVICE_STATUS" = "ACTIVE" ]; then
          echo "Updating existing ECS service..."
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment \
            --region $AWS_REGION
        else
          echo "Creating new ECS service..."
          aws ecs create-service \
            --cluster $CLUSTER_NAME \
            --service-name $SERVICE_NAME \
            --task-definition $TASK_DEF_NAME \
            --desired-count 1 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[\"$SUBNET_IDS\"],securityGroups=[\"$SECURITY_GROUP_IDS\"],assignPublicIp=\"ENABLED\"}" \
            --region $AWS_REGION
        fi
