
spring:
  datasource:
    url: jdbc:mysql://vatest-db.cby6eiqg8v59.us-east-1.rds.amazonaws.com:3306/vatest
    username: root
    password: rajaiah12311
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never  # Prevents Spring Boot from executing schema.sql/data.sql if they exist

sonarqube:
  url: http://localhost:9000
  token: your_generated_sonarqube_token
